# Generated by Django 4.2.9 on 2024-03-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_new_rename_category_author_delete_product_new_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.TextField(default='new'),
        ),
    ]
